# Generated by Django 3.0.1 on 2019-12-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesize',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('b', 'Bike'), ('eb', 'Electric bike'), ('s', 'Scooter'), ('es', 'Electric scooter')], default='b', max_length=2, unique=True),
        ),
    ]
