# Generated by Django 3.0.1 on 2019-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20191225_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(choices=[('b', 'Bike'), ('eb', 'Electric bike'), ('s', 'Scooter'), ('es', 'Electric scooter')], max_length=2, unique=True),
        ),
    ]
